### ISSUE TITLE
Translating NewDevice notification

### ISSUE THREAD

**Issue by SRWieZ** [yadahan/laravel-authentication-log#1]
Hi!

First of all, I really like your package, it's working great.
I'm making a French website and I can't (or don't know how) translate the subject of notifications.

Can you add a translation file or maybe use laravel localization function ?
https://laravel.com/docs/5.5/localization#retrieving-translation-strings

Best regards.

**Comment by yakidahan** [comment]
Hi,

Thank you for using this package.

I added translation support in the new release [v1.1.0](https://github.com/yadahan/laravel-authentication-log/releases/tag/v1.1.0).

To translate the email notification you need to publish the email view by `php artisan vendor:publish --tag=authentication-log-views` command, and edit the content in `/resources/views/vendor/authentication-log/emails/new.blade.php` file.

To translate the sms/slack notification just publish the translations files by `php artisan vendor:publish --tag=authentication-log-translations` command, and add your translations in `/resources/lang/vendor/authentication-log` folder.

**Comment by SRWieZ** [comment]
Awesome!

Tested and I'm able to change the subject now. :)

Thanks.

**Comment by yakidahan** [comment]
You're welcome!
