### ISSUE TITLE
Not working with multiple authentications

### ISSUE THREAD

**Issue by MicVital** [yadahan/laravel-authentication-log#14]
I tried integrating it into a project that has multiple multiple guards (normal user and admin). It works alright for a normal user but for the admin guard. I get this error after logging in:

> Call to undefined method App\Admin::authentications()
I'm quite confused as to what to do. Any help?

**Comment by yakidahan** [comment]
Hi @MicVital 

Add the `AuthenticationLogable` and `Notifiable` traits to your guards models.

```php
use Illuminate\Notifications\Notifiable;
use Yadahan\AuthenticationLog\AuthenticationLogable;

class Admin
{
    use Notifiable, AuthenticationLogable;
}
```
