### ISSUE TITLE
Suggest : Add location to sent event email

### ISSUE THREAD

**Issue by AEK-BKF** [yadahan/laravel-authentication-log#24]
Hello,

Thanks for this nice package,
You may add user location to be sent.

You can use this package : https://github.com/Torann

Thanks.

**Comment by TechTailor** [comment]
If possible, can you create a PR for the same with tests.

**Comment by TechTailor** [comment]
@AEK-BKF are you sure about the accuracy of this detector? I have had some bad experiences using others which end up showing very inaccurate locations. If this one is good, I will open a PR for it.

-TT
