### ISSUE TITLE
How to get all user log history

### ISSUE THREAD

**Issue by odion-cloud** [yadahan/laravel-authentication-log#25]
this error come out when try to get all user history for admin user 'where' not 'find'

Exception
Property [authentications] does not exist on this collection instance.

**Comment by TechTailor** [comment]
You need to add the trait `AuthenticationLogable ` to your User Model. Check the configuration section in the Readme.

-TT

**Comment by jhoanborges** [comment]
1 Create a model

`<?php

namespace App;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AuthenticationLogs extends Model
{
	protected $guarded = ['id'];
	protected $fillable = [];
    protected $table = 'authentication_log';

     
    public function user()
    {
        return $this
        ->hasOne('App\User', 'id', 'authenticatable_id');
    }
}
`

2. Call the relationship like this in your controller }

`    
use App\AuthenticationLogs;
public function getAuthLogs()
    {
        $data = AuthenticationLogs::with('user')
        ->get();
        return response()->json($data, 200);
    }
`

**Comment by TechTailor** [comment]
> 1 Create a model
> 
> ```
> 
> <?php
> 
> namespace App;
> 
> use Illuminate\Database\Eloquent\Factories\HasFactory;
> use Illuminate\Database\Eloquent\Model;
> 
> class AuthenticationLogs extends Model
> {
> 	protected $guarded = ['id'];
> 	protected $fillable = [];
>     protected $table = 'authentication_log';
> 
>      
>     public function user()
>     {
>         return $this
>         ->hasOne('App\User', 'id', 'authenticatable_id');
>     }
> }
> ```
> 
> 2. Call the relationship like this in your controller }
> 
> `use App\AuthenticationLogs;`
> 
> ```
> public function getAuthLogs()
>     {
>         $data = AuthenticationLogs::with('user')
>         ->get();
>         return response()->json($data, 200);
>     }
> ```

Hey, that's not how you are supposed to do that. Please read the documents again. 

You just need to add the `AuthenticationLogable` trait as shown in the docs. 

```use Illuminate\Notifications\Notifiable;
use Yadahan\AuthenticationLog\AuthenticationLogable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, AuthenticationLogable;
}
