### ISSUE TITLE
Call to a member function diffInMinutes() on string

### ISSUE THREAD

**Issue by bhavingajjar** [yadahan/laravel-authentication-log#27]
![image](https://user-images.githubusercontent.com/11258397/102875688-21d8a380-446a-11eb-8586-5cdfa06461d8.png)
getting this error in laravel after upgrading v1.3.0 => v1.4.1

**Comment by TechTailor** [comment]
Hello,

Oh yeah the {$user->getCreatedAtColumn()} seems to be the culprit here. I will take a look and send a fix once I get home. 

Until then you can replace the $newUser with the following for a temporary fix (in the vendor files) -

`$newUser = $user->created_at->diffInMinutes(Carbon::now()) < 1;`

-TT

**Comment by bhavingajjar** [comment]
https://github.com/yadahan/laravel-authentication-log/pull/28
if possible please merge this PR so i can update composer for fix this issue

**Comment by yakidahan** [comment]
Hi @bhavingajjar,

I'm unable to recover this error


`composer require yadahan/laravel-authentication-log:1.4.0`

**Comment by yakidahan** [comment]
Hi @bhavingajjar,

The `$user->created_at` == `$user->{$user->getCreatedAtColumn()}` so I'm not sure that's the issue.

I'm unable to recover this error, can you please provide me with your environment information?
PHP version: ?
Laravel version: ?

Please try this syntax and update if it solves your issue:
`$newUser = Carbon::parse($user->{$user->getCreatedAtColumn()})->diffInMinutes(Carbon::now()) < 1;`

You can downgrade to version `1.4.0` to get the `$user->created_at` syntax:
`composer require yadahan/laravel-authentication-log:1.4.0`

**Comment by rydje** [comment]
Hello,

First, thank you @yakidahan for this great package.

I'm having the same issue, but on my case `$user->created_at` is not a string but a DateTimeImmutable.
I'll downgrade to 1.4.0 until the issue is fixed.

**Comment by yakidahan** [comment]
@rydje @bhavingajjar
Please check if the new release [v1.4.2](https://github.com/yadahan/laravel-authentication-log/releases/tag/v1.4.2) solves this issue.
