### ISSUE TITLE
How to test this

### ISSUE THREAD

**Issue by zakblacki** [yadahan/laravel-authentication-log#29]
Documentation not clear 
![image](https://user-images.githubusercontent.com/29728429/103325074-622bb900-4a4a-11eb-979a-77cbe6bd0cae.png)

Where do I put theses ?  and where do I find the logs stored ? or access them

**Comment by TechTailor** [comment]
You can put these where ever you wanna access them. Want to access logs in a controller, use these in a controller, wanna do it in a view, then use it there. 

If want to see exactly what's being returned just dd it inside a controller (or even the route file for testing).

-TT
