### ISSUE TITLE
Method Illuminate\Database\Query\Builder::authentications does not exist.

### ISSUE THREAD

**Issue by Q8root** [yadahan/laravel-authentication-log#3]
Method Illuminate\Database\Query\Builder::authentications does not exist.

After installing i got this error when trying to login in and logout 

 public function __call($method, $parameters)
    {
        if (static::hasMacro($method)) {
            return $this->macroCall($method, $parameters);
        }
 
        if (Str::startsWith($method, 'where')) {
            return $this->dynamicWhere($method, $parameters);
        }
 
        throw new BadMethodCallException(sprintf(
            'Method %s::%s does not exist.', static::class, $method
        ));
    }
}
 
Arguments
"Method Illuminate\Database\Query\Builder::authentications does not exist."

**Comment by yakidahan** [comment]
Seems you missed to add `AuthenticationLogable` trait to your `App\User` model, See the [Configuration](https://github.com/yadahan/laravel-authentication-log#configuration) section.
