### ISSUE TITLE
[Feature] Discussion regarding a feature to block devices

### ISSUE THREAD

**Issue by TechTailor** [yadahan/laravel-authentication-log#32]
I am not really sure if this feature should even be within the scope of this package, but I recently had a requirement for such a feature on a project of mine and thought it would come in handy as part of this package.

Since this package notifies a user of login from an unknown device, adding a button in the alert email which calls a method to block that device seems useful. Of course, this will require adding a column (is_blocked) to the log table and the users will have to retain the logs indefinitely (unless we modify the log cleaner to ignore any "blocked" records). 

@yakidahan would be happy to get your input on this before submitting a pr for it.

Also, I am still debating whether the block should be on the device, ip or on the combination of IP & device (but then the same device on a new IP would no longer be blocked).

-TT

**Comment by MacPafety** [comment]
The block should be in combination of both device and ip
