### ISSUE TITLE
How to make it works with Laravel Passport?

### ISSUE THREAD

**Issue by HuyNguyen206** [yadahan/laravel-authentication-log#34]
Currently, when I login via laravel passport (Password Grant Tokens), it doesn't record this login information in authentication_log table.

**Comment by TechTailor** [comment]
For ref. look into the `src/Listeners/` folder. This package listens for the Auth Events (Login/Logout). So if you want this package to update the data when using passport, be sure to call the laravel's login event

**Comment by HuyNguyen206** [comment]
Thanks @TechTailor,
As checked, can i use these two events for login and logout?
 **1.Login event**
```
event(new \Illuminate\Auth\Events\Login(
            $this->guard(),
            $user,
            false
        ));
```
**2. Logout event**
```
event(new \Illuminate\Auth\Events\Logout(
            $this->guard(),
            $user
        ));
```

**Comment by ILABUTK** [comment]
This worked for me (Passport):
```
        $user = $request->user();
        event(new \Illuminate\Auth\Events\Logout(
            auth()->guard(),
            $user
        )); // to trigger logout event

        $request->user()->token()->revoke();

```

> Thanks @TechTailor,
> As checked, can i use these two events for login and logout?
> **1.Login event**
> 
> ```
> event(new \Illuminate\Auth\Events\Login(
>             $this->guard(),
>             $user,
>             false
>         ));
> ```
> 
> **2. Logout event**
> 
> ```
> event(new \Illuminate\Auth\Events\Logout(
>             $this->guard(),
>             $user
>         ));
> ```
