### ISSUE TITLE
Log failed auth login attempts

### ISSUE THREAD

**Issue by howdu** [yadahan/laravel-authentication-log#35]
Are there any plans to add in failed auth attempts via: \Illuminate\Auth\Events\Failed?

Currently handle this separately but would be nice to have it in one package. E.g
https://brayniverse.com/monitoring-failed-login-attempts-with-laravel.html

**Comment by TechTailor** [comment]
The purpose of this package is to identify logins from new devices and alert users of the same so they can change their password (if needed). Failed logins means no one accessed their accounts so no reason to warm or track that. Laravel already has rate limiting so no question of brute force.

I just don't get the use case (common enough) in which logging failed attempts would be useful.

-TT

**Comment by howdu** [comment]
Thanks yeah that all makes sense cheers.
