### ISSUE TITLE
manaually  update one record 

### ISSUE THREAD

**Issue by kazemimorteza68** [yadahan/laravel-authentication-log#40]
How can i find last record current authenticated user and update that records data ?
 especially i want update logout time and when recall logout method that last record not be changed again automatically.

Thanks

**Comment by TechTailor** [comment]
Hello, 

You can refer to PR #31 to get an idea of how to do that. Since this repo isn't accepting pr's, I ended up forking it and creating my own with the additions I required (you can check my profile for repo link).

-TT
