### ISSUE TITLE
Laravel 11 Support Needed

### ISSUE THREAD

**Issue by prof-usman** [yadahan/laravel-authentication-log#54]
### Laravel 11 Support Needed

yadahan/laravel-authentication-log v1.6.0 requires illuminate/support ^7.30.4|^8.40.0|^9.0|^10.0 -> satisfiable by illuminate/support[v7.30.4, v7.30.5, v7.30.6, v8.40.0, ..., v8.83.27, v9.0.0-beta.1, ..., v9.52.16, v10.0.0, ..., v10.48.2].

**Comment by yakidahan** [comment]
Hi,

Thank you for using this package.

I added Laravel 11 support in the new release [v1.7.0](https://github.com/yadahan/laravel-authentication-log/releases/tag/v1.7.0).
