### ISSUE TITLE
Notification Queue

### ISSUE THREAD

**Issue by ben182** [yadahan/laravel-authentication-log#8]
Hi it would be really nice if we can queue the notifications. You simply have to implement the ShouldQueue interface. https://laravel.com/docs/5.7/notifications#queueing-notifications

https://github.com/yadahan/laravel-authentication-log/blob/d6297e9f573305325effa4b0fa48e5b9f6b36144/src/Notifications/NewDevice.php#L12

**Comment by TechTailor** [comment]
Hey, thanks for the input. If you got time, please create a pull-request with your intended addition/change. If it gets the job done, it will surely get merged. I will take a look at it myself when I get home.

-TT
